/**
 * Inline src/ modules into an n8n Code-node body.
 *
 * n8n Code nodes cannot import local files, so the only way to keep this
 * pipeline's logic under test is to write it as ordinary ES modules, import
 * them normally in vitest, and mechanically inline the same source into the
 * node bodies at build time. One implementation, two consumers, no copy-paste
 * drift - and scripts/pull-workflow.mjs re-extracts these regions from the live
 * workflow to prove the running instance still matches git.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

export const beginMarker = (name) => `// ==BEGIN INLINED ${name}==`;
export const endMarker = (name) => `// ==END INLINED ${name}==`;

/** Strip module syntax so the source is valid inside a Code node. */
export function stripModuleSyntax(source, name) {
  if (/^\s*import\s/m.test(source)) {
    throw new Error(`${name} has an import statement; inlined modules must be dependency free`);
  }
  if (/^\s*export\s+default\s/m.test(source)) {
    throw new Error(`${name} uses a default export; use named exports so inlining stays mechanical`);
  }
  return source
    .replace(/^export\s+(const|let|function|class|async\s+function)\b/gm, '$1')
    .replace(/^export\s*\{[^}]*\};?[ \t]*$/gm, '')
    .trimEnd();
}

export function readModule(relPath) {
  const source = readFileSync(join(ROOT, relPath), 'utf8');
  return `${beginMarker(relPath)}\n${stripModuleSyntax(source, relPath)}\n${endMarker(relPath)}`;
}

/** Read every context/ file the prompts need, as one inlinable const. */
export function readContextPack() {
  const read = (p) => readFileSync(join(ROOT, 'context', p), 'utf8').trim();
  const exampleDir = join(ROOT, 'context', 'examples');
  const examples = readdirSync(exampleDir)
    .filter((f) => f.endsWith('.md') && f !== 'README.md')
    .sort()
    .map((f) => readFileSync(join(exampleDir, f), 'utf8').trim());

  const pack = {
    rubric: read('rubric.md'),
    profile: read('profile.md'),
    proposalRules: read('proposal-rules.md'),
    examples,
  };
  return `${beginMarker('context/')}\nconst CONTEXT_PACK = ${JSON.stringify(pack, null, 2)};\n${endMarker('context/')}`;
}

/**
 * Compose a Code-node body from inlined modules plus the node's own logic.
 * @param {string[]} modules relative paths under the repo root
 * @param {string} logic the node-specific code
 * @param {{context?: boolean}} [opts]
 */
export function codeNodeBody(modules, logic, opts = {}) {
  const parts = [
    '// GENERATED by scripts/build-workflow.mjs - do not edit in the n8n UI.',
    '// Edit the module under src/ (or context/), run ./test.sh, re-import.',
    '',
  ];
  for (const m of modules) parts.push(readModule(m), '');
  if (opts.context) parts.push(readContextPack(), '');
  parts.push('// ---- node logic ----', logic.trim(), '');
  return parts.join('\n');
}

/** Pull the inlined regions back out of a Code-node body, for drift checks. */
export function extractInlinedRegions(body) {
  const out = {};
  const re = /\/\/ ==BEGIN INLINED (.+?)==\n([\s\S]*?)\n\/\/ ==END INLINED \1==/g;
  let m;
  while ((m = re.exec(body)) !== null) out[m[1]] = m[2];
  return out;
}
